Repository gdt050579/GView, pull requests merged in 2024-03, with the labels that each got.

#240 Miscelaneous improvements
  GView/src/GView.cpp
  GViewCore/src/App/Instance.cpp
  GViewCore/src/include/Internal.hpp
Labels: Enhancement, Development

#242 Dissasm view added collapsible zones now fully working
  GViewCore/src/View/DissasmViewer/DissasmKeyEvents.cpp
  GViewCore/src/View/DissasmViewer/DissasmViewer.hpp
  GViewCore/src/View/DissasmViewer/DissasmX86.cpp
  GViewCore/src/View/DissasmViewer/Instance.cpp
  GViewCore/src/View/DissasmViewer/tests_dissasmviewer.cpp
Labels: Bug, Enhancement, Development

#245 Closes #244 fixed the Windows version not being set properly on Windows binaries at details
  .gitignore
  CMakeLists.txt
  GView/CMakeLists.txt
  GViewCore/CMakeLists.txt
  cmake/windows.rc.in
  cmake/windows_resource.cmake
Labels: Bug

#253 Closes #249. Fixed GView not loading config when it doesn't exist
  GViewCore/src/App/Instance.cpp
Labels: Bug

#259 Dissasm fix some bugs with comments and added automatic unit testing job
  .github/workflows/testing.yml
  CMakeLists.txt
  GViewCore/src/View/DissasmViewer/DissasmViewer.hpp
  GViewCore/src/View/DissasmViewer/Instance.cpp
  GViewCore/src/View/DissasmViewer/tests_dissasmviewer.cpp
  GViewCore/src/View/DissasmViewer/x86_x64/DissasmX86.cpp
  GViewCore/src/View/DissasmViewer/x86_x64/DissasmX86.hpp
Labels: Bug, Enhancement

#197 177 core add docker support
  docker/Dockerfile
Labels: Development

#264 [Docs] + MacOS first run instructions
  .github/workflows/deploy_release.yml
  README.md
Labels: Documentation

#270 [ZIP] # fix path separator sent to container view from ZIP plugin #24…
  GViewCore/src/View/ContainerViewer/ContainerViewer.hpp
  GViewCore/src/View/ContainerViewer/Settings.cpp
  Types/ZIP/src/ZIPFile.cpp
  Types/ZIP/src/zip.cpp
Labels: Bug

#274 271 update project readme + fix BestMatch in core
  GViewCore/src/App/Instance.cpp
  README.md
  docs/source/_static/logo.png
Labels: Enhancement

#279 277 dissasm add button to hide or show opcodes and text to give the user the option to view only the dissasm
  GViewCore/src/View/DissasmViewer/Config.cpp
  GViewCore/src/View/DissasmViewer/Config.hpp
  GViewCore/src/View/DissasmViewer/DissasmKeyEvents.cpp
  GViewCore/src/View/DissasmViewer/DissasmProperties.cpp
  GViewCore/src/View/DissasmViewer/x86_x64/DissasmX86.cpp
Labels: Enhancement

#275 251 gview add tutorial pictures with explanations when gview is first opened when gviewini is not found
  GViewCore/src/App/CMakeLists.txt
  GViewCore/src/App/Instance.cpp
  GViewCore/src/App/TutorialWindow.cpp
  GViewCore/src/include/Internal.hpp
Labels: Enhancement

#284 FIxed #234. Now dissasm viewer takes into account if it has focus or not
  GViewCore/src/View/DissasmViewer/Config.cpp
  GViewCore/src/View/DissasmViewer/Config.hpp
  GViewCore/src/View/DissasmViewer/DissasmViewer.hpp
  GViewCore/src/View/DissasmViewer/Instance.cpp
  GViewCore/src/View/DissasmViewer/jclass/DissasmJClass.cpp
  GViewCore/src/View/DissasmViewer/x86_x64/DissasmX86.cpp
Labels: Bug
