Repository gdt050579/GView, pull requests merged in 2024-04, with the labels that each got.

#290 Miscelaneous fixes
  CMakeLists.txt
  GViewCore/src/View/DissasmViewer/x86_x64/DissasmX86.cpp
  cmake/generic_plugin.cmake
  cmake/type.cmake
Labels: Bug, Development

#292 Dissasm view
  GViewCore/src/View/DissasmViewer/Instance.cpp
  GViewCore/src/View/DissasmViewer/x86_x64/DissasmX86.cpp
Labels: Bug, Enhancement

#293 dissasm fixed latest change that was breaking tests
  GViewCore/src/View/DissasmViewer/x86_x64/DissasmX86.cpp
Labels: Bug

#281 192 eml email electronic mail format plugin
  CMakeLists.txt
  GViewCore/include/GView.hpp
  GViewCore/src/CMakeLists.txt
  GViewCore/src/Unpack/Base64.cpp
  GViewCore/src/Unpack/CMakeLists.txt
  GenericPlugins/Unpackers/CMakeLists.txt
  GenericPlugins/Unpackers/include/Unpackers.hpp
  GenericPlugins/Unpackers/src/CMakeLists.txt
  GenericPlugins/Unpackers/src/Unpackers.cpp
  Types/EML/CMakeLists.txt
  Types/EML/include/eml.hpp
  Types/EML/src/CMakeLists.txt
  Types/EML/src/EMLFile.cpp
  Types/EML/src/PanelInformation.cpp
  Types/EML/src/eml.cpp
  Types/EML/src/generate_b64_tables.py
Labels: Enhancement

#302 300 eml add more descriptions to the eml plugin
  GViewCore/src/View/DissasmViewer/Instance.cpp
  Types/EML/include/eml.hpp
  Types/EML/src/EMLFile.cpp
  Types/EML/src/eml.cpp
Labels: Enhancement
